Add form_factor field to screenshot member
w3c/manifest-app-info pull request #59
Opened 2022-08-23 19:05 UTC by philloooo

2022-08-23 19:13 UTC, philloooo commented
@aarongustafson please take a look! I will submit the follow up CL for removing the `screenshot` field after this one is merged.

2022-08-23 22:20 UTC, aarongustafson requested changes

2022-08-23 22:20 UTC, aarongustafson commented on index.html
> +        form_factor (e.g., Android phone shouldn't show wide form_factor
```suggestion
        form factor (e.g., Android phone shouldn't show "wide" `form_factor`
```

2022-08-23 22:22 UTC, aarongustafson commented
Looks good @philloooo. Thanks!

2022-09-12 16:18 UTC, philloooo commented
@aarongustafson  can you merge this?

2022-10-05 23:36 UTC, marcoscaceres commented on index.html
> +        The <code><dfn class="export">form_factor</dfn></code> member is a
```suggestion
        The <code><dfn data-for="manifest" class="export">form_factor</dfn></code> member is a
```

2022-10-05 23:39 UTC, marcoscaceres approved these changes

2022-10-05 23:41 UTC, marcoscaceres commented on index.html
> +        form factor (e.g., Android phone shouldn't show "wide" `form_factor`
```suggestion
        form factor (e.g., mobile phones shouldn't show "wide" `form_factor`
```

2022-10-05 23:48 UTC, merged